### ISSUE TITLE
TOS.hyp always displays pages in German

### ISSUE THREAD

**Issue by vinz6751** [freemint/tos.hyp#103] opened 2021-07-02 16:43 UTC
Dear team, 

I noticed that since a few days, urls like
https://freemint.github.io/tos.hyp/**en**/index.html

or any page from TOS.hyp are in German
The link https://freemint.github.io/tos.hyp/ (linked from the former site http://toshyp.atari.org/en/index.html)  is broken too.
I use Firefox. I tried disabling the privacy settings for the site but it didn't help.
Any clue ?

**Comment by mikrosk** [comment] 2021-07-03 05:55
@th-otto any chance this is caused by your recent CI changes?

**Comment by th-otto** [comment] 2021-07-03 06:07
On Samstag, 3. Juli 2021 07:55:59 CEST Miro Kropáček wrote:
> @th-otto any chance this is caused by your recent CI changes?

Yes it is. Should be fixed now.

**Closed** 2022-01-06 15:35 UTC
